Translated to Czech
Cobweb-Aclevo/celos pull request #36
Opened 2021-07-16 16:38 UTC by VojtechTM

i translated the accesibility slide to czech

2021-07-16 16:39 UTC, whyadamsalt commented
Would it be fine if you translated all of the others too? It would be easier if all the slides were translated otherwise contributors may not realize that only one of them have been done.

2021-07-16 16:42 UTC, VojtechTM commented
Yeah, im planning to do that, but i have only 15 mins of internet so i just pushed this

2021-07-16 16:49 UTC, whyadamsalt commented
That's fine, is it alright if we merge once all are translated?

2021-07-16 16:53 UTC, VojtechTM commented
Yeah, of course!

2021-07-16 16:54 UTC, VojtechTM commented
Managed to translate 3 pages today, gonna do the rest tommorow

2021-07-16 16:57 UTC, whyadamsalt commented
Okay that's brilliant, thank you!

2021-07-20 22:05 UTC, whyadamsalt commented
Are all of the pages done?

2021-08-10 17:50 UTC, whyadamsalt commented
I want to follow up, are all of the pages done for the translation?

2021-08-10 18:38 UTC, VojtechTM commented
Sorry i've been really busy, im gonna try to finish it up by saturday

2021-08-13 18:32 UTC, VojtechTM commented
You can know merge it into mainstream!

2021-08-13 18:44 UTC, locness3 requested changes
I don't speak any Czech but I feel like there are some typos

2021-08-13 18:44 UTC, locness3 commented on Assets/ubiquity-slideshow/slides/cs/gethelp.html
> +<p>At <a href="http://askubuntu.com">Ask Ubuntu</a> Můžete se zeptat na otázky a hledat ve velké kolekci už odpovězených otázek</p>
Is the "At" translated here?

2021-08-13 18:44 UTC, locness3 commented on Assets/ubiquity-slideshow/slides/cs/gethelp.html
> +<p>Pro další užitečné informace jděte na <a href="https://www.ubuntu.com/support/community-support">Ubuntu komunitní podopra</a> or <a href="http://www.ubuntu.com/support">Ubuntu komerční podpora</a>
Same for the "or"?

2021-08-13 18:44 UTC, locness3 commented on Assets/ubiquity-slideshow/slides/cs/photos.html
> +	<p class="caption">Shotcut Video Editor</p>
Forgot to translate?

2021-08-13 18:45 UTC, VojtechTM commented on Assets/ubiquity-slideshow/slides/cs/gethelp.html
> +<p>At <a href="http://askubuntu.com">Ask Ubuntu</a> Můžete se zeptat na otázky a hledat ve velké kolekci už odpovězených otázek</p>
sorry, didnt notice that

2021-08-13 18:47 UTC, VojtechTM commented on Assets/ubiquity-slideshow/slides/cs/photos.html
> +	<p class="caption">Shotcut Video Editor</p>
Thats the same

2021-08-13 18:48 UTC, locness3 commented on Assets/ubiquity-slideshow/slides/cs/photos.html
> +	<p class="caption">Shotcut Video Editor</p>
I mean, it looks like you've translated the names of all other programs. Why would you leave this one intact?

2021-08-13 18:51 UTC, VojtechTM commented
fixed the typos.

2021-08-13 18:54 UTC, VojtechTM commented on Assets/ubiquity-slideshow/slides/cs/photos.html
> +	<p class="caption">Shotcut Video Editor</p>
because video editor is the same in czech

2021-08-13 19:00 UTC, locness3 approved these changes

2021-11-09 12:30 UTC, VojtechTM commented
Was the translation commited? cant seem to find it

2021-11-09 17:35 UTC, locness3 commented
It wasn't, as you can see the PR is still open. I've been working on improving the folder structure, so I'll have to update this pr after that.

2021-11-10 18:17 UTC, VojtechTM commented
ok, let me know if you need any help

2021-11-10 22:20 UTC, locness3 commented
Any help on #48 would be very appreciated.

2021-11-20 18:16 UTC, VojtechTM commented
I've had shortend the readme file, and created a docs folder where ive put the packages

2021-11-20 18:29 UTC, locness3 commented
Please create another PR for the beta7 branch.

2021-11-20 18:30 UTC, locness3 commented
Closing this for now.

2021-11-20 18:30 UTC, closed without merging